name: python_project
channels:
  - conda-forge
dependencies:
  - python 
  - matplotlib
  - notebook
  - numpy
  - rise
  - pandas
  - pip
  - scipy
  - mdtraj
  - cmake
  - yaml
  - ruamel_yaml
  - clang_osx-64 
  - clangxx_osx-64
